groups['meta-bundles'] = {
    'member_patterns': (
        r'.*',
    ),
    'bundles': (
        'authorized_key',
        'backup_client',
        'backup_server',
        'base',
        'co2mon',
        'controller',
        'cron',
        'dhcpclient',
        'dotfiles',
        'git',
        'golang',
        'group',
        'grub',
        'hostname',
        'iptables',
        'kernel_modules',
        'locale',
        'monit',
        'mosquitto',
        'networking',
        'nginx',
        'samba',
        'smart',
        'ssh',
        'sudo',
        'sysctl',
        'timezone',
        'ubuntu-desktop',
        'user',
        'zfs',
    ),
}
