groups['meta-bundles'] = {
    'member_patterns': (
        r'.*',
    ),
    'bundles': (
        'authorized_key',
        'backup_client',
        'backup_server',
        'base',
        'co2mon',
        'cron',
        'dhcpclient',
        'dns-update',
        # 'docker-compose',
        # 'docker-engine',
        # 'docker-login',
        'dotfiles',
        'git',
        'group',
        'grub',
        'haproxy',
        'hostname',
        'iptables',
        'kernel_modules',
        # 'kubernetes',
        'kvm',
        'locale',
        'monit',
        'mosquitto',
        'networking',
        'nfs-server',
        'nginx',
        'ntp',
        'openhab',
        'openvpn',
        'puppet',
        'samba',
        'smart',
        'ssh',
        'sudo',
        'sysctl',
        'timemachine',
        'timezone',
        'tomcat7',
        'ubuntu-desktop',
        'user',
        'zfs',
    ),
}
