#!/usr/bin/env bash

# Enable IP-Forwarding
echo 1 > /proc/sys/net/ipv4/ip_forward

#
# Define policy
#
iptables -P INPUT ACCEPT
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT

#
# Delete all rules
#
iptables -t nat -F
iptables -t filter -F
iptables -t mangle -F
iptables -X -t nat
iptables -X -t filter
iptables -X -t mangle
iptables -Z -t nat
iptables -Z -t filter
iptables -Z -t mangle

#
# Create Custom Chains
#
iptables -N CUSTOM-INPUT
iptables -N CUSTOM-FORWARD
iptables -N CUSTOM-OUTPUT
iptables -t nat -N CUSTOM-PREROUTING
iptables -t nat -N CUSTOM-POSTROUTING

#
# Recreate all custom chains
#
#iptables -D INPUT -j CUSTOM-INPUT
iptables -I INPUT -j CUSTOM-INPUT

#iptables -D FORWARD -j CUSTOM-FORWARD
iptables -I FORWARD -j CUSTOM-FORWARD

#iptables -D OUTPUT -j CUSTOM-OUTPUT
iptables -I OUTPUT -j CUSTOM-OUTPUT

#iptables -t nat -D PREROUTING -j CUSTOM-PREROUTING
iptables -t nat -I PREROUTING -j CUSTOM-PREROUTING

#iptables -t nat -D POSTROUTING -j CUSTOM-POSTROUTING
iptables -t nat -I POSTROUTING -j CUSTOM-POSTROUTING

#
# Allow localhost
#
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

#
# Allow output
#
iptables -A OUTPUT -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT

#
# Allow answers
#
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

#
# Ports
#
# Ping
iptables -A INPUT -p icmp --icmp-type 8 -j ACCEPT
iptables -A INPUT -p icmp --icmp-type 11 -j ACCEPT
# SSH
iptables -A INPUT -m state --state NEW --protocol tcp --dport 22 -j ACCEPT
