#!/usr/bin/env bash

#
# Define policy
#
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

#
# Recreate all custom chains
#
iptables -D INPUT -j CUSTOM-INPUT
iptables -D FORWARD -j CUSTOM-FORWARD
iptables -D OUTPUT -j CUSTOM-OUTPUT

iptables -F CUSTOM-INPUT
iptables -F CUSTOM-FORWARD
iptables -F CUSTOM-OUTPUT

iptables -X CUSTOM-INPUT
iptables -X CUSTOM-FORWARD
iptables -X CUSTOM-OUTPUT

iptables -N CUSTOM-INPUT
iptables -N CUSTOM-FORWARD
iptables -N CUSTOM-OUTPUT

iptables -A INPUT -j CUSTOM-INPUT
iptables -A FORWARD -j CUSTOM-FORWARD
iptables -A OUTPUT -j CUSTOM-OUTPUT

iptables -t nat -D PREROUTING -j CUSTOM-PREROUTING
iptables -t nat -D POSTROUTING -j CUSTOM-POSTROUTING

iptables -t nat -F CUSTOM-PREROUTING
iptables -t nat -F CUSTOM-POSTROUTING

iptables -t nat -X CUSTOM-PREROUTING
iptables -t nat -X CUSTOM-POSTROUTING

iptables -t nat -N CUSTOM-PREROUTING
iptables -t nat -N CUSTOM-POSTROUTING

iptables -t nat -A PREROUTING -j CUSTOM-PREROUTING
iptables -t nat -A POSTROUTING -j CUSTOM-POSTROUTING

#
# Natd
#
% for nat_interface in nat_interfaces:
iptables -t nat -A CUSTOM-POSTROUTING -o ${nat_interface} -s 10.0.0.0/8 -j MASQUERADE
iptables -t nat -A CUSTOM-POSTROUTING -o ${nat_interface} -s 172.16.0.0/12 -j MASQUERADE
iptables -t nat -A CUSTOM-POSTROUTING -o ${nat_interface} -s 192.168.0.0/16 -j MASQUERADE
% endfor

#
# Allow localhost
#
iptables -A CUSTOM-INPUT -i lo -j ACCEPT
iptables -A CUSTOM-OUTPUT -o lo -j ACCEPT

#
# Allow output
#
iptables -A CUSTOM-OUTPUT -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT

#
# Allow answers
#
iptables -A CUSTOM-INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

#
# Ports
#
# Ping
iptables -A CUSTOM-INPUT -p icmp --icmp-type 8 -j ACCEPT
iptables -A CUSTOM-INPUT -p icmp --icmp-type 11 -j ACCEPT
# SSH
iptables -A CUSTOM-INPUT -m state --state NEW --protocol tcp --dport 22 -j ACCEPT

#
# Custom rules
#
% for rule in rules:
${rule}
% endfor

#
# Logging
#
iptables -A CUSTOM-INPUT -j LOG --log-prefix="IPTABLES-INPUT: "
iptables -A CUSTOM-OUTPUT -j LOG --log-prefix="IPTABLES-OUTPUT: "
iptables -A CUSTOM-FORWARD -j LOG --log-prefix="IPTABLES-FORWARD: "
