#!/usr/bin/env bash

#
# Define policy
#
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

#
# Recreate all custom chains
#
iptables -D INPUT -j CUSTOM-INPUT
iptables -I INPUT -j CUSTOM-INPUT

iptables -D FORWARD -j CUSTOM-FORWARD
iptables -I FORWARD -j CUSTOM-FORWARD

iptables -D OUTPUT -j CUSTOM-OUTPUT
iptables -I OUTPUT -j CUSTOM-OUTPUT

iptables -t nat -D PREROUTING -j CUSTOM-PREROUTING
iptables -t nat -I PREROUTING -j CUSTOM-PREROUTING

iptables -t nat -D POSTROUTING -j CUSTOM-POSTROUTING
iptables -t nat -I POSTROUTING -j CUSTOM-POSTROUTING

#
# Flush custom chains
#
iptables -F CUSTOM-INPUT
iptables -F CUSTOM-FORWARD
iptables -F CUSTOM-OUTPUT

iptables -Z CUSTOM-INPUT
iptables -Z CUSTOM-FORWARD
iptables -Z CUSTOM-OUTPUT

iptables -t nat -F CUSTOM-PREROUTING
iptables -t nat -F CUSTOM-POSTROUTING

iptables -t nat -Z CUSTOM-PREROUTING
iptables -t nat -Z CUSTOM-POSTROUTING

#
# Natd
#
% for nat_interface in nat_interfaces:
iptables -t nat -A CUSTOM-POSTROUTING -o ${nat_interface} -s 10.0.0.0/8 -j MASQUERADE
iptables -t nat -A CUSTOM-POSTROUTING -o ${nat_interface} -s 172.16.0.0/12 -j MASQUERADE
iptables -t nat -A CUSTOM-POSTROUTING -o ${nat_interface} -s 192.168.0.0/16 -j MASQUERADE
% endfor

#
# Custom rules
#
% for rule in rules:
${rule}
% endfor
