
dev tun
port 563
proto tcp4
server 172.16.90.0 255.255.255.0
ca /etc/openvpn/keys/ca.crt
cert /etc/openvpn/keys/server.crt
key /etc/openvpn/keys/server.key
dh /etc/openvpn/keys/dh.pem
tls-auth /etc/openvpn/keys/ta.key 0
ifconfig-pool-persist ip_pool
keepalive 10 120
cipher AES-256-CBC
persist-key
persist-tun
status server.status
topology subnet
# comp-lzo
client-config-dir /etc/openvpn/ccd
push "route 172.16.90.0 255.255.255.0"
client-to-client

# route to 192.168.178.0/24 via opnsense 
route 192.168.178.0 255.255.255.0 172.16.90.10

verb 3
log /var/log/openvpn/server.log

 
