#!/usr/bin/env bash

if [ -z $1 ] || [ -z $2 ]; then
echo "Usage: codeyard-passwords NODENAME USERNAME"
exit 1
fi

bw debug -c "print(repo.vault.password_for('user {user} node {node}'.format(node='$1',user='$2'), length=16))"
