[global]
workgroup = box
server string = ${server_name}
security = user
log file = /var/log/samba/log.%m
max log size = 1000
% for name, share in sorted(shares.items()):

[${name}]
	comment = ${share.get('comment', name)}
	path = ${share['path']}
	browsable = ${share.get('browsable', 'yes')}
	valid users = ${share['valid_users']}
	read only = ${share.get('read_only', 'no')}
	create mask = ${share.get('create_mask', '0660')}
	directory mask = ${share.get('directory_mask', '0770')}
% if 'force_user' in share:
	force user = ${share['force_user']}
% endif
% if 'force_group' in share:
	force group = ${share['force_group']}
% endif
	veto files = /.DS_Store/._*/
	delete veto files = yes
% endfor
% if homes.get('enabled', False):

[homes]
	comment = Home Directories
	browseable = no
	valid users = ${' '.join(homes.get('valid_users', []))}
	writable = yes
	read only = no
	create mask = 0600
	directory mask = 0700
	veto files = /.DS_Store/._*/
	delete veto files = yes
% endif
